version: 2.1

orbs:
  helm: circleci/helm@1.2.0
  aws-ecr: circleci/aws-ecr@6.15.3
  kubernetes: circleci/kubernetes@0.11.2
commands:
  setup-aws-profiles:
    steps:
      - run:
          name: aws profiles setup
          command: |
            npx @syngenta-digital/acp --file ./aws/profiles.yml
            aws sts get-caller-identity
jobs:
  build-and-push-image:
    working_directory: /tmp/build
    docker:
      - image: circleci/openjdk:11-stretch
    steps:
      - aws-cli/setup
      - checkout
      - run: echo "Hello, docker!"
      - setup-aws-profiles
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          profile-name: <<parameters.profile>>
          path: .
          region: DEV_AWS_REGION
          repo: poccicd
          tag: <<parameters.tag>>
  deploy:
    working_directory: /tmp/build
    docker:
      - image: docker:20.10.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t my-image .
            
     

workflows:
  build-and-deploy:
    jobs:
      - build-and-push-image
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master